services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - "80:80"
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile.w1
    ports:
      - "8080:8080"
    networks:
      default:
        aliases:
          - web