services:
  proxy:
    image: nginx:latest
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./files/proxy/default:/etc/nginx/conf.d/default.conf

  web:
    image: nginx:latest
    volumes:
      - ./files/w1/default:/etc/nginx/conf.d/default.conf
      - ./files/w1/html:/var/www/w1/html/index.html